# 問題1：行列積を手計算する

$$
A = \begin{bmatrix}
-1 & 2 & 3 \\\ 
4 & -5 & 6 \\\
7 & 8 & -9
\end{bmatrix},
B=\begin{bmatrix}
0 & 2 & 1 \\\ 
0 & 2 & -8 \\\
2 & 9 & -1
\end{bmatrix}
$$

<p>[手計算]</p>
$$
AB=\begin{bmatrix}
(-1*0 + 2*0 + 3*2) & (-1*2 + 2*2 + 3*9) & (-1*1 + 2*-8 + 3*-1) \\\
(4*0 + -5*0 + 6*2) & (4*2 + -5*2 + 6*9) & (4*1 + -5*-8 + 6*-1) \\\
(7*0 + 8*0 + -9*2) & (7*2 + 8*2 + -9*9) & (7*1 + 8*-8 + -9*-1)
\end{bmatrix}
$$
$$
AB=\begin{bmatrix}
6 & 29 & -20 \\\
12 & 52 & 38 \\\
-18 & -51 & -48
\end{bmatrix}
$$

___
# 問題2：NumPyの関数による計算

In [37]:
import numpy as np

matrix_a = np.array([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
matrix_b = np.array([[0, 2, 1],[0, 2, -8],[2, 9, -1]])

print("----- @ ------")
print(matrix_a@matrix_b)
print("----- np.matmul() ------")
print(np.matmul(matrix_a, matrix_b))
print("----- np.dot() ------")
print(np.dot(matrix_a, matrix_b))

----- @ ------
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
----- np.matmul() ------
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
----- np.dot() ------
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


___
# 問題3：ある要素の計算を実装

In [59]:
ROWS = 3
COLUMNS = 3

matrix_ab = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])

for row in range(ROWS):
    for col in range(COLUMNS):
        total = 0
        for i in range(COLUMNS):
            total = total + matrix_a[row][i]*matrix_b[i][col]
        matrix_ab[row][col] = total

print(matrix_ab)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


___
# 問題4：行列積を行う関数の作成
# 問題5：計算が定義されない入力を判定する
# 問題5：転置
<p>＊ 3問題を以下のセルでまとめて扱う</p>

In [151]:
ROW = 0
COL = 1

def multiple_matrix(mtx_a, mtx_b):
    
    mtx_a_shape = mtx_a.shape
    mtx_b_shape = mtx_b.shape
    
    matrix_list = np.array(np.zeros(mtx_a_shape[ROW]*mtx_b_shape[COL], int))
    if mtx_a_shape[ROW] == mtx_a_shape[COL] == mtx_b_shape[ROW] == mtx_b_shape[COL]:
        matrix_list = matrix_list.reshape(mtx_a_shape[ROW], mtx_a_shape[COL])
    else:
        matrix_list = matrix_list.reshape(mtx_a_shape[ROW], mtx_b_shape[COL])

    # Prevent calculate in case not match mtx_a columns to mtx_b rows
    if mtx_a_shape[COL] != mtx_b_shape[ROW]:
        print("Can't multiple matrix in this case.")
        print("mtx_a columns is {}, mtx_b rows is {}".format(mtx_a_shape[COL], mtx_b_shape[ROW]))
        pass
    else:
        for row in range(mtx_a_shape[ROW]):
            for col in range(mtx_b_shape[COL]):
                cell_total = 0
                for i in range(mtx_a_shape[COL]):
                    cell_total = cell_total + mtx_a[row][i]*mtx_b[i][col]
                matrix_list[row][col] = cell_total
                
        return matrix_list

print(multiple_matrix(matrix_a, matrix_b))

print("--------------------------------")

### 問題5の”計算が定義されない”パターンを実施
test_matrix_a = np.array([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
test_matrix_b = np.array([[0, 2, -8],[2, 9, -1]])
print(multiple_matrix(test_matrix_a, test_matrix_b))

print("--------------------------------")

### 問題6の”転置”パターンを実施
print(multiple_matrix(test_matrix_a, test_matrix_b.T))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
--------------------------------
Can't multiple matrix in this case.
mtx_a columns is 3, mtx_b rows is 2
None
--------------------------------
[[-20  13]
 [-58 -43]
 [ 88  95]]
